name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Deploy website
        run: |
          ssh -o StrictHostKeyChecking=no cardgames@192.168.0.24 '
            cd /home/cardgames/cardgames.party &&
            git pull origin main &&
            docker-compose down &&
            docker-compose up -d
          '